---

- name: copy the identity cert and the CA bundle
  copy: src={{ env_name }}/{{ item }} dest=/etc/httpd/keys/{{ item }} owner=root group=root mode=0644
  with_items:
    - identity.pem
    - ca_bundle.pem
  notify:
    - restart httpd

#- name: https private key
#  copy: dest=/etc/httpd/keys/private.key content="{{ ssl_private_key | vault }}" owner=root group=root mode=0600
#  notify:
#    - restart httpd
